"""Add demand models from jobs

Revision ID: 1e42a12186da
Revises: e4a05b88d90b
Create Date: 2025-12-19 10:24:30.448114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e42a12186da"
down_revision: str | Sequence[str] | None = "e4a05b88d90b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_enrichments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("excitement_score", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("signals", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("context_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_enrichments_company_name"),
        "company_enrichments",
        ["company_name"],
        unique=True,
    )
    op.create_table(
        "role_briefings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paraform_id", sa.String(length=100), nullable=False),
        sa.Column("detail_raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("meeting_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("profile_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pitch_summary", sa.Text(), nullable=False),
        sa.Column("key_selling_points", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("day_to_day", sa.Text(), nullable=True),
        sa.Column("requirements_must_have", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("requirements_nice_to_have", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("interview_stages", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("interview_timeline", sa.String(length=100), nullable=True),
        sa.Column("interview_prep_notes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("application_questions", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("info_to_gather", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("red_flags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("score_at_enrichment", sa.Float(), nullable=False),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_briefings_paraform_id"), "role_briefings", ["paraform_id"], unique=True
    )
    op.create_table(
        "role_enrichments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paraform_id", sa.String(length=100), nullable=False),
        sa.Column("extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("positive_signals", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("negative_signals", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("investors", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("funding_stage", sa.String(length=50), nullable=True),
        sa.Column("extracted_location", sa.String(length=100), nullable=True),
        sa.Column("extracted_location_confidence", sa.String(length=20), nullable=True),
        sa.Column("source_company_tip", sa.Text(), nullable=True),
        sa.Column("source_selling_points", sa.Text(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_enrichments_paraform_id"), "role_enrichments", ["paraform_id"], unique=True
    )
    op.create_table(
        "role_scrape_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("roles_found", sa.Integer(), nullable=False),
        sa.Column("new_roles", sa.Integer(), nullable=False),
        sa.Column("updated_roles", sa.Integer(), nullable=False),
        sa.Column("qualified_roles", sa.Integer(), nullable=False),
        sa.Column("skipped_unchanged", sa.Integer(), nullable=False),
        sa.Column("errors", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("triggered_by", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_scrape_runs_run_id"), "role_scrape_runs", ["run_id"], unique=True)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_dashboard_visit", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_digest_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paraform_id", sa.String(length=100), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("is_qualified", sa.Boolean(), nullable=False),
        sa.Column("qualification_tier", sa.String(length=20), nullable=True),
        sa.Column("qualification_reasons", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("disqualification_reasons", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), nullable=False),
        sa.Column("last_seen_in_scrape_id", sa.Integer(), nullable=True),
        sa.Column("disappeared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("engineer_score", sa.Float(), nullable=True),
        sa.Column("headhunter_score", sa.Float(), nullable=True),
        sa.Column("excitement_score", sa.Float(), nullable=True),
        sa.Column("combined_score", sa.Float(), nullable=True),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_seen_in_scrape_id"],
            ["role_scrape_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_combined_score"), "roles", ["combined_score"], unique=False)
    op.create_index(op.f("ix_roles_content_hash"), "roles", ["content_hash"], unique=False)
    op.create_index(op.f("ix_roles_engineer_score"), "roles", ["engineer_score"], unique=False)
    op.create_index(op.f("ix_roles_first_seen_at"), "roles", ["first_seen_at"], unique=False)
    op.create_index(op.f("ix_roles_headhunter_score"), "roles", ["headhunter_score"], unique=False)
    op.create_index(op.f("ix_roles_is_qualified"), "roles", ["is_qualified"], unique=False)
    op.create_index(op.f("ix_roles_lifecycle_status"), "roles", ["lifecycle_status"], unique=False)
    op.create_index(op.f("ix_roles_paraform_id"), "roles", ["paraform_id"], unique=True)
    op.create_index(
        op.f("ix_roles_qualification_tier"), "roles", ["qualification_tier"], unique=False
    )
    op.create_table(
        "role_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("scrape_run_id", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["scrape_run_id"],
            ["role_scrape_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_changes_change_type"), "role_changes", ["change_type"], unique=False
    )
    op.create_index(
        op.f("ix_role_changes_detected_at"), "role_changes", ["detected_at"], unique=False
    )
    op.create_index(op.f("ix_role_changes_role_id"), "role_changes", ["role_id"], unique=False)
    op.create_index(
        op.f("ix_role_changes_scrape_run_id"), "role_changes", ["scrape_run_id"], unique=False
    )
    op.create_table(
        "role_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("scrape_run_id", sa.Integer(), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("salary_upper", sa.Integer(), nullable=True),
        sa.Column("percent_fee", sa.Float(), nullable=True),
        sa.Column("hiring_count", sa.Integer(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["scrape_run_id"],
            ["role_scrape_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_snapshots_role_id"), "role_snapshots", ["role_id"], unique=False)
    op.create_index(
        op.f("ix_role_snapshots_scrape_run_id"), "role_snapshots", ["scrape_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_role_snapshots_scraped_at"), "role_snapshots", ["scraped_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_snapshots_scraped_at"), table_name="role_snapshots")
    op.drop_index(op.f("ix_role_snapshots_scrape_run_id"), table_name="role_snapshots")
    op.drop_index(op.f("ix_role_snapshots_role_id"), table_name="role_snapshots")
    op.drop_table("role_snapshots")
    op.drop_index(op.f("ix_role_changes_scrape_run_id"), table_name="role_changes")
    op.drop_index(op.f("ix_role_changes_role_id"), table_name="role_changes")
    op.drop_index(op.f("ix_role_changes_detected_at"), table_name="role_changes")
    op.drop_index(op.f("ix_role_changes_change_type"), table_name="role_changes")
    op.drop_table("role_changes")
    op.drop_index(op.f("ix_roles_qualification_tier"), table_name="roles")
    op.drop_index(op.f("ix_roles_paraform_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_lifecycle_status"), table_name="roles")
    op.drop_index(op.f("ix_roles_is_qualified"), table_name="roles")
    op.drop_index(op.f("ix_roles_headhunter_score"), table_name="roles")
    op.drop_index(op.f("ix_roles_first_seen_at"), table_name="roles")
    op.drop_index(op.f("ix_roles_engineer_score"), table_name="roles")
    op.drop_index(op.f("ix_roles_content_hash"), table_name="roles")
    op.drop_index(op.f("ix_roles_combined_score"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_role_scrape_runs_run_id"), table_name="role_scrape_runs")
    op.drop_table("role_scrape_runs")
    op.drop_index(op.f("ix_role_enrichments_paraform_id"), table_name="role_enrichments")
    op.drop_table("role_enrichments")
    op.drop_index(op.f("ix_role_briefings_paraform_id"), table_name="role_briefings")
    op.drop_table("role_briefings")
    op.drop_index(op.f("ix_company_enrichments_company_name"), table_name="company_enrichments")
    op.drop_table("company_enrichments")
    # ### end Alembic commands ###
